#!/usr/bin/env bash
# Script to install haproxy load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend codingbennet-frontend
	bind *:80
	mode http
	default_backend codingbennet-backend
backend codingbennet-backend
	balance roundrobin
	server 373394-web-01 35.174.209.78:80 check
	server 373394-web-02 54.167.174.202:80 check
"
echo "$server_config" |sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart 
